### ISSUE TITLE
Accessing the company opportunities

### ISSUE THREAD

**Issue by Mansuro** [jessicard/remote-jobs#118]
Many of the companies listed don't have a link/item on the menu on their website for the jobs they are offering. I am wondering if such companies belong to the list

**Comment by mastermind1981** [comment]
+1 . we should make a cleanup and have the link to the openings jobs directly

**Comment by dougaitken** [comment]
This should be listed on the company profile under "How to apply", this should list either the vacancy or clear direct how someone can find out about any openings. 
If the company doesn't have a profile, then I'm sure they'll be backfilled in soon

**Comment by blundell** [comment]
fwiw we don't have direct job openings with specific titles on the website because we are always hiring - if you are a great person with technical skills and learning attitude we'll hire you even when there is no "job title on our website"

**Comment by dougaitken** [comment]
@blundell Sorry, not sure why I missed this. Do you have anywhere on your website that prospective applicants can find this sort of info?

**Comment by blundell** [comment]
It's kind of implicit in our website https://www.novoda.com/hiring i.e. we don't have job openings but we tell them to apply!

**Comment by dougaitken** [comment]
Sorry @blundell, replied to this then saw your PR. Sorted now 👍
