### ISSUE TITLE
CartoDB doesn't seem to be remote

### ISSUE THREAD

**Issue by webmaven** [jessicard/remote-jobs#153]
No remote positions listed: https://cartodb.com/jobs/

**Comment by dougaitken** [comment]
A quick google shows that positions in the past have allowed remote. 

Also, this position is ["based in our Madrid office, although we often work remotely."](https://cartodb.com/jobs/junior-designer/)

**Comment by webmaven** [comment]
> This position is based in our Madrid office, although we often work remotely.

That basically says to me that employees must come into the office sometimes, but have permission to often work from home (which would still be in Madrid). IOW **not** a remote work job at all.

**Comment by dougaitken** [comment]
Ah, I think that comes down to the company -i.e. will they fund the trip or is it "required but not subsidised"

**Comment by webmaven** [comment]
Well, let's ask the guy that added CartoDB in the first place: @javierarce, I see you are also located in Madrid. Can you comment on what your company means by *'we often work remotely'*?

**Comment by javierarce** [comment]
Hi! Please, see my answer here to a similar question [here](https://github.com/jessicard/remote-jobs/pull/15#issuecomment-147771498). 

While it's true that we don't explicitly announce the possibility to work remotely in our job openings, any employee can work wherever he or she wants. 

We currently have several people working 100% remote and also several other people work partially remote (i.e: they come to the Madrid office once every one or two weeks). 

It's true that we aren't a 100% remote company, but we are definitely remote-friendly. 

https://twitter.com/cartoDB/status/520496981077422080

**Comment by ethervoid** [comment]
I'm a CartoDB employee that works almost completely in remote. I only go to the Madrid office one day per week but is not mandatory, other coworkers works completely in remote.

**Comment by dougaitken** [comment]
So it's basically, if you want to come into the office to hang out, that's cool, otherwise just do your own thing. 
Cheer for the clarification again @javierarce, and @ethervoid.

**Comment by ethervoid** [comment]
You're welcome :)

**Comment by webmaven** [comment]
Thanks @javierarce and @ethervoid, I am closing this issue.
