### ISSUE TITLE
Coupa does not seem to be remote

### ISSUE THREAD

**Issue by webmaven** [jessicard/remote-jobs#154]
http://www.coupa.com/careers/openings/

**Comment by dougaitken** [comment]
Like #153 it looks like the jobs allow remote, I'm guessing Coupa have been included as they may have posted on WeWorkRemotely or something

**Comment by webmaven** [comment]
@dougaitken:
>  it looks like the jobs allow remote

Can you point me to an example? My google-fu is failing me.

**Comment by dougaitken** [comment]
This is a dated but it is remote for them http://iisrar.com/jobsremotely/job/programming-and-tech/ruby-on-rails-developer-multiple-openings-at-coupa-software-san-mateo-ca-allows-remote-2/

**Comment by webmaven** [comment]
@dougaitken, in my humble opinion, companies should not be represented in this list just because *at some time in the past* they used to hire remote employees (and no longer seem to).

**Comment by dougaitken** [comment]
I think this is tricky point - there are a lot of companies in this list who are not hiring right now, so should they be included? This resource is a starting point for companies who support remote working. I think a discussion needs to take place around this, and it fits with #54 - i.e. what is the extent of remote, how often is remote an option, and everything surrounding remote working.

**Comment by webmaven** [comment]
Keep in mind that while that discussion is worth having, Coupa [is definitely hiring right now](http://www.coupa.com/careers/openings/). 

@jessicard, it looks like Coupa was included by you in the initial batch of companies, can you comment where that original data came from, and/or what criteria you applied when gathering it?: fd17dc3

**Comment by jessicard** [comment]
Ah, I believe that came from either a tweet or a website provided to me. Mind a PR to remove?

**Comment by webmaven** [comment]
@jessicard Not at all.

**Comment by jessicard** [comment]
Fixed in #155/#156!
