### ISSUE TITLE
Add a column for the type of the jobs

### ISSUE THREAD

**Issue by mastermind1981** [jessicard/remote-jobs#165]
Adding another column for the type of the jobs offered by the companies. The column will contain values like : IT, Web design, Writing ....

**Comment by dougaitken** [comment]
Interesting idea but it would become cluttered in the current layout :-1: 

I think this might be something Jessica may have thoughts on but my take is that most of these companies will offer a range of roles. 
If there is a move to a website of the information, it could be something filterable. However I think this repository is great as it gives information about the company to allow you to decide if you want to work for them - also I've seen a lot of companies state something like "email us if there isn't a job opening for you but you're interested". :+1:

**Comment by Joel-James** [comment]
+1 for this.

**Comment by venediktov** [comment]
instead of type of jobs column please add column describing programming stack/system those companies utilize e.g javascript , HTML5 ,  angularJS, node.js , Java, C#, C++ , Unix , MacOS , Linux , etc.

**Comment by dougaitken** [comment]
Hi @venediktov this isn't entirely developer based so that column type wouldn't mean anything to someone looking for a Customer Support role. Like I was. 

These are companies who fall under the "tech" umbrella and who hire remotely. That's it.

**Comment by glauberramos** [comment]
I think it would be useful the have the type of the company as well, like which industry it belongs, technology, health, etc...

**Comment by dougaitken** [comment]
I can see the use for this @glauberramos, this repo started as:

> A list of semi to fully remote-friendly companies in or around tech.

I will give it some thought, and look at including this in the ideas in #44

**Comment by dougaitken** [comment]
Closing in favour of #44
