### ISSUE TITLE
Maybe note which are US-only?

### ISSUE THREAD

**Issue by garann** [jessicard/remote-jobs#24]
There are a few companies on that list who are remote, but only within the same timezones as the US, or even within the physical United States. If the intent is to create a US-specific list I guess it doesn't matter much, but the use of "remote" to mean "you can work from SF _or_ NYC!" can be a little confusing if you're international. Noting which are US-only would be an awesome addition, if practical. 

Thanks for putting this together!

**Comment by jessicard** [comment]
This is a great idea! We should add a column for this :+1:

**Comment by jessicard** [comment]
Added a column in https://github.com/jessicard/remote-jobs/commit/3c4ed6891d7a8e1f603119fec5afdd8b8b9a7a91. Added it to the contributing guidelines.
