### ISSUE TITLE
IBM no longer remote-friendly?

### ISSUE THREAD

**Issue by tamouse** [jessicard/remote-jobs#279]
I've been seeing [reports](https://www.theregister.co.uk/2017/02/09/ibm_workfromhome_cull_companywide/?mt=1487279104379) and personally from family and friends who work there, that IBM is pulling in all remote employees and forcing them to work in regional offices.

**Comment by dougaitken** [comment]
Hey @tamouse, great point! We have only a placeholder for IBM in this repo, so I'll go ahead and get that removed as there hasn't been any participation relating to them here.

**Comment by dougaitken** [comment]
Resolve in #265
