### ISSUE TITLE
WeWorkRemotely

### ISSUE THREAD

**Issue by whatasunnyday** [jessicard/remote-jobs#34]
WeWorkRemotely is a job board for remote only jobs run by Basecamp.

I noticed that most of the companies that post there were missing from this list.

This issue is to remind myself to add the companies to the list. If this issue has no updates after 24 hours, you can assume I forgot and take over.

https://weworkremotely.com/

**Comment by jessicard** [comment]
Thanks @whatasunnyday! :sparkles:
