### ISSUE TITLE
add an attribute to company linkedin page

### ISSUE THREAD

**Issue by chovy** [jessicard/remote-jobs#340]
This would be a lot easier using linkedin to find a recruiter at the company than digging through career pages.

**Comment by dougaitken** [comment]
I can give it some thought.

From my experience, reaching out to recruiters via LinkedIn is often the slowest/spammiest way, and if you can't follow the instructions on careers/jobs page then I'm unsure why it exists.

**Comment by fool** [comment]
Hmm, I like the simple format that is here already.  If someone submitting a company thinks that the link to a linkedin, or angel list, or glassdoor, or other profile is relevant to the hiring process, they are welcome to put it in the footer.  Adding a field for every website on the planet, or merely the most predatory job-related-social-network on the planet doesn't really buy us anything IMNSHO

**Comment by dougaitken** [comment]
WFM ^
