### ISSUE TITLE
How much information is needed to submit a PR

### ISSUE THREAD

**Issue by dougaitken** [jessicard/remote-jobs#65]
I noticed that the read has been expanded, and there are submission guidelines. I was going to submit a few companies but some of the information I'm not able to locate, what is needed to submit a PR and how much can be added later?

**Comment by jessicard** [comment]
The only requirements are the name and the website. I should add that to the README. However, if I notice other info missing, I'll ask for it in the PR. If you don't have it, just mention that in the PR description, and I'll merge it without bugging you :)

**Comment by jessicard** [comment]
I added some additional information about this in the README here: https://github.com/jessicard/remote-jobs/commit/007d4b629b100004c36e538767fd5273e00bc371 Thanks!
