### ISSUE TITLE
Tech stack section

### ISSUE THREAD

**Issue by jenkoian** [jessicard/remote-jobs#82]
Can do a PR but wanted to bring it up for discussion first. Think it's worth having a column for tech stack of the company? I know tech stack is sometimes transient but may be helpful for scanning the list (which is only going to grow) if only interested in certain tech.

(Great idea btw :+1:)

**Comment by hkdobrev** [comment]
@jenkoian That's already included in the [example company profile](https://github.com/jessicard/remote-jobs/blob/master/company-profiles/example.md#company-technologies) and people are already contributing these in the company profiles.

Having tech stack as a column in the table would increase the table width and possible the height of the rows as well. I think this is better left for a [future GitHub pages version of the list](https://github.com/jessicard/remote-jobs/issues/44).

**Comment by jenkoian** [comment]
ah didn't even notice the company profile thing, cheers.

**Comment by jessicard** [comment]
Appreciate it! :) Thanks for the feedback.
