### ISSUE TITLE
Use JSON for company profiles

### ISSUE THREAD

**Issue by hkdobrev** [jessicard/remote-jobs#88]
Similar to [JSON Résumé](http://jsonresume.org/) and [json-job](https://github.com/lukasz-madon/json-job).

If the company profiles are in JSON, various lists and apps could be created on top of it client-side similar to http://emoji.muan.co/ - see source: https://github.com/muan/emojilib/blob/master/emojis.json

**Comment by tedmiston** [comment]
Great idea.  I've been looking for something like JSON Resume for so long.  Thanks for the share.

**Comment by jessicard** [comment]
:+1: Good call.

**Comment by zeke** [comment]
:clap:

**Comment by eddiejaoude** [comment]
Great list! Is this still part of the plan?

I have converted the `markdown` list of companies to `json` https://github.com/WeRockTech/remote-jobs/commit/bbcdff85099f17af4fb943ba68ef0458ca4b2f5e that way it can be moved to a web app and put on GitHub Pages

**Comment by dougaitken** [comment]
Closing and any discussion can happen in #44 to keep things central. 

Will look to getting this done during Hacktoberfest 2017 (if it happens) as I think will be a nice 2-year reminder for how I got into this
